@hostname = localhost
@port = 3001
@personId = 6374c49d647b07ee725f5905
@missingPersonId = 5fb7a52d0cf00d5c090c1c75
@host = http://{{hostname}}:{{port}}

###

GET {{host}}/api/persons/{{personId}} HTTP/1.1
Accept: application/json

###

GET {{host}}/api/persons/{{missingPersonId}} HTTP/1.1
Accept: application/json