@hostname = localhost
@port = 3001
@host = http://{{hostname}}:{{port}}

###

POST {{host}}/createPerson HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "name": "bouzebal 2.0",
  "number":"0059900909090"
}


