@hostname = localhost
@port = 3001
@personId = 637372f1438b37ade96f1147

@host = http://{{hostname}}:{{port}}

### supprimer une personne par son /:id

DELETE {{host}}/delete/{{personId}} HTTP/1.1
Accept: application/json


