@hostname = localhost
@port = 3001
@host = http://{{hostname}}:{{port}}
@personId = 6374cb670f4d49b4ded1829c


### mettre a jour une personne par son /:id

PUT {{host}}/update/{{personId}} HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "name": "bouzebal",
  "number": "12-34-5678901234"
}


